instance:
  _target_: teleoperation.camera.camera_multi.CameraRealsenseMulti
  keys:
    top: 239722071918
    left_wrist: 419122271348
    right_wrist: 419122271585
  camera_config:
    fps: 30
    width: 640
    height: 480
    use_depth: ${use_depth}
  display_config:
    key: "top"
    mode: "mono"
    resolution: [480, 640]
    crop_sizes: [0, 0, 0, 0]
