use_real_hand: false
use_real_robot: false

wait_time: 5.0

frequency: 50

joint_filter:
  min_cutoff: 0.01
  beta: 10.0

hand_filter:
  min_cutoff: 0.0001
  beta: 20.0

head_filter:
  alpha: 0.7

left_hand_prefix: "L_"
right_hand_prefix: "R_"

hand:
  config: "fourier.yml"
  prefix_left: "L_"
  prefix_right: "R_"
  ip_left: "192.168.137.39"
  ip_right: "192.168.137.19"

robot:
  urdf_path: "gr1/urdf/robot.urdf"
  urdf_package_dirs: ["gr1/urdf", "gr1"]
  # urdf_path: "gr1_inspire/urdf/t2_collision.urdf"
  # urdf_package_dirs: ["gr1_inspire/urdf"]

  joint_names:
    [
      "left_hip_roll_joint",
      "left_hip_yaw_joint",
      "left_hip_pitch_joint",
      "left_knee_pitch_joint",
      "left_ankle_pitch_joint",
      "left_ankle_roll_joint",
      "right_hip_roll_joint",
      "right_hip_yaw_joint",
      "right_hip_pitch_joint",
      "right_knee_pitch_joint",
      "right_ankle_pitch_joint",
      "right_ankle_roll_joint",
      "waist_yaw_joint",
      "waist_pitch_joint",
      "waist_roll_joint",
      "head_pitch_joint",
      "head_roll_joint",
      "head_yaw_joint",
      "left_shoulder_pitch_joint",
      "left_shoulder_roll_joint",
      "left_shoulder_yaw_joint",
      "left_elbow_pitch_joint",
      "left_wrist_yaw_joint",
      "left_wrist_roll_joint",
      "left_wrist_pitch_joint",
      "right_shoulder_pitch_joint",
      "right_shoulder_roll_joint",
      "right_shoulder_yaw_joint",
      "right_elbow_pitch_joint",
      "right_wrist_yaw_joint",
      "right_wrist_roll_joint",
      "right_wrist_pitch_joint",
    ]

  visualize: true
  display_collisions: false
  displayed_frames:
    # - "right_ee_frame"
    # - "left_ee_frame"
    - "r_hand_base_link"
    - "l_hand_base_link"
    - "base_link"
    - "torso_link"
    - "head_yaw_link"

  self_collision:
    enable: false
    min_distance: 0.02
    enabled_links: ["right_hand_yaw_link", "left_hand_yaw_link", "torso_link"]

  joints_to_lock: [
      "waist_roll_joint",
      "head_roll_joint",
      "waist_yaw_joint",
      # "waist_pitch_joint",
    ]

  # frames:
  #   - name: "right_end_effector_link"
  #     parent: "right_hand_roll_link"
  #   - name: "left_end_effector_link"
  #     parent: "left_hand_roll_link"

  joint_limits:
    left_shoulder_pitch_joint: [-2.27, 0.3]
    right_shoulder_pitch_joint: [-2.27, 0.3]

    left_shoulder_roll_joint: [0, 1.57]
    right_shoulder_roll_joint: [-1.57, 0]

    left_shoulder_yaw_joint: [-2.09, 2.09]
    right_shoulder_yaw_joint: [-2.09, 2.09]

    left_elbow_pitch_joint: [-2.27, 0.3]
    right_elbow_pitch_joint: [-2.27, 0.3]

    waist_yaw_joint: [-0.5, 0.5]
    waist_pitch_joint: [-0.08, 0.35] # [-10, 20]

    left_wrist_pitch_joint: [-0.6, 0.6]
    left_wrist_roll_joint: [-0.87, 0.87]

    right_wrist_pitch_joint: [-0.6, 0.6]
    right_wrist_roll_joint: [-0.87, 0.87]

  velocity_limits:
    waist_yaw_joint: 1.0
    waist_pitch_joint: 0.3
    head_pitch_joint: 1.0
    head_yaw_joint: 1.0
    left_shoulder_roll_joint: 6.283185307179586
    left_shoulder_pitch_joint: 6.283185307179586
    left_shoulder_yaw_joint: 6.283185307179586
    left_elbow_pitch_joint: 6.283185307179586
    left_wrist_yaw_joint: 6.283185307179586
    left_wrist_pitch_joint: 6.283185307179586
    left_wrist_roll_joint: 6.283185307179586
    right_shoulder_roll_joint: 6.283185307179586
    right_shoulder_pitch_joint: 6.283185307179586
    right_shoulder_yaw_joint: 6.283185307179586
    right_elbow_pitch_joint: 6.283185307179586
    right_wrist_yaw_joint: 6.283185307179586
    right_wrist_pitch_joint: 6.283185307179586
    right_wrist_roll_joint: 6.283185307179586

  body_scaling_factor: 1.0

  position_filter:
    min_cutoff: 0.01
    beta: 1.0

  orientation_filter:
    alpha: 0.6
