defaults:
  - teleop
  - hand: fourier_dexpilot
  - robot: ??? # e.g. "robot: 'gr1t2'"
  - camera: ??? # e.g. "camera: 'oak_97'"
  - _self_

debug: false
debug_hand: false
sim: false
wait_time: 3.0
frequency: 60
use_waist: false
use_head: false
use_depth: false
task_name: ??? # e.g. "task_name: 'task_name'"

recording:
  enabled: true
  task_name: ${task_name}

upsampler:
  frequency: 250
  gravity_compensation: true
