defaults:
  - teleop
  - hand: fourier
  - robot: gr1t2
  - camera: zed
  - _self_


debug: false
debug_hand: false
sim: false
wait_time: 3.0
frequency: 60
use_waist: false
use_head: false


recording:
  enabled: true
  task_name: "default"

upsampler:
  frequency: 120
  gravity_compensation: true
